services:

  api:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  worker:
    build: ./backend
    command: node src/workers/analysis.worker.js
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  frontend:
    build: ./frontend/arvyax-journal
    ports:
      - "3000:3000"
    depends_on:
      - api

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"